name: Sanity

on:
  pull_request:

permissions:
  contents: read

jobs:
  sanity:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Sanity Check Script
        run: " bash sanity.sh"
