name: Sanity

on:
  pull_request:

jobs:
  sanity:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@v3

      - name: Run Sanity Check Script
        run: " bash sanity.sh"
